spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: gateway-proxy
          uri: ${proxy.url}
          predicates:
            - Path=/**